(#204) Updated Breadcrumbs tests
NCIOCPL/cgov-digital-platform-acceptance-tests pull request #227
Opened 2022-10-05 21:13 UTC by kate-mashkina

Closes #204

2022-11-01 14:46 UTC, sarinapadilla commented
This PR looks good to me!

2022-11-07 17:32 UTC, bryanpizzillo requested changes
Can you please add a check that the title of the page also have the `aria-current="page"` attribute? This allows users with assistive devices to know this is where they are.

(I should have asked for it in the sidenav. :( )

2022-11-07 18:12 UTC, KateMashkinaNIH commented
> Can you please add a check that the title of the page also have the `aria-current="page"` attribute? This allows users with assistive devices to know this is where they are.
> 
> (I should have asked for it in the sidenav. :( )

added step And current page breadcrumb has an attribute "aria-current" with value "page"

2022-11-08 18:37 UTC, bryanpizzillo approved these changes

2022-11-08 18:37 UTC, merged