Ticket/253 mini landing page test
NCIOCPL/cgov-digital-platform-acceptance-tests pull request #322
Opened 2022-12-27 21:33 UTC by ahmadakbaryNIH

added feature 
added definitions

2022-12-28 22:28 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/209880724-869e453d-4805-4526-96c6-ae8a86858ef8.png)
![image](https://user-images.githubusercontent.com/114245453/209880838-d21fdcc5-a455-4fd1-ada4-d1c78dac69ff.png)
![image](https://user-images.githubusercontent.com/114245453/209880852-66b655f8-fd04-43d6-9319-c6d8a71b4514.png)

2022-12-29 00:51 UTC, KateMashkinaNIH requested changes

2022-12-29 00:51 UTC, KateMashkinaNIH commented on cypress.config.js
> +    front_end_base_url: 'https://www-test-acsf.cancer.gov'
revert this change - it should not be committed, you only change values to test locally and revert back after

2022-12-29 00:51 UTC, KateMashkinaNIH commented on cypress.config.js
> +    baseUrl: 'https://www-cms-test.cancer.gov',
same here - revert the change pls

2022-12-29 00:51 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$MiniLandingPageTest/index.js
> +    cy.get("div[class='ajax-new-content'] input[class='js-text-full text-full form-text']").type(value)
bad locator - use input[name^='field_landing_contents[0][subform][field_content_heading]'] instead

2022-12-29 00:51 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$MiniLandingPageTest/index.js
> +    cy.get(`input[value='${dropDown}']`).click({ force: true })
this step doesn't exist in the feature file - remove

2022-12-29 00:51 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$MiniLandingPageTest/index.js
> +    cy.get(`input[value='${title}']`).click({ force: true })
this step doesn't exist in the feature file - remove

2022-12-29 00:51 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$MiniLandingPageTest/index.js
> +
remove all of the extra empty lines here

2023-01-03 15:48 UTC, KateMashkinaNIH approved these changes

2023-01-03 15:48 UTC, merged