(#310)CancerTypeHomePage-FrontEndVerification
NCIOCPL/cgov-digital-platform-acceptance-tests pull request #378
Opened 2023-02-24 04:47 UTC by ahmadakbaryNIH

closes # 310

2023-02-24 04:47 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/221094193-32486a6e-a96e-4316-be5f-7c3bc6c52224.png)

2023-02-27 02:55 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/221462342-38fe08bf-97a7-4344-b43b-1587ee92aba7.png)

2023-02-28 05:59 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/221767055-9431b25b-0884-49b0-84bb-9e116cb109e5.png)
![image](https://user-images.githubusercontent.com/114245453/221767080-0dbf42b7-6f59-42c8-b08c-d46a35f34057.png)
![image](https://user-images.githubusercontent.com/114245453/221767183-cafa21d1-abc4-4b86-8c59-9b2eeb67b92a.png)
![image](https://user-images.githubusercontent.com/114245453/221767244-f5922031-5108-4950-a4be-85c9928b916c.png)

2023-03-06 03:14 UTC, ahmadakbaryNIH commented
$CancerTypeHomePagefrontEndVerification
![image](https://user-images.githubusercontent.com/114245453/223011335-a6df1b23-d75c-4461-ab17-8dc91be35184.png)

2023-03-06 20:14 UTC, KateMashkinaNIH requested changes

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get("div[class='equalheight bgWhite cthp-causes'] a").should('have.attr', 'href', replacedTestSiteSection)
the locator can be changed to div[class*='cthp-causes'] a
also, make use of aliases so you do not repeat your code
cy.get("div[class='equalheight bgWhite cthp-causes'] a").as('card').should('have.text', linkText)
    cy.get('@ card').should('have.attr', 'href', replacedTestSiteSection)

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get(`div[class='equalheight bgWhite cthp-survival'] a:contains("${title}")`).should('be.visible').and('have.attr', 'href', href)
this should be handled like a step above ( also, update class locator how I suggested above a well) 
cy.get("").as('card').should('have.text', linkText)
cy.get('@ card').should('have.attr', 'href', replacedTestSiteSection)

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get(`div[class='equalheight bgWhite cthp-survival'] a:contains("${title}")`).should('be.visible').and('have.attr', 'href', href)
no space after @

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get("div[class='equalheight bgWhite cthp-screening'] a").should('have.text', linkText)
pls update locator 
and do the same I suggested for two prev steps

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get("div[class='equalheight bgWhite cthp-general'] p").should('be.visible')
update locator
also, just checking that it is visible is not enough - you should add that it is not empty

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +})
this does not check for links at all 
you should be checking that div[class*='cthp-general'] a ).length is more than 0

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get(`div[class='equalheight bgWhite cthp-research'] a`).should('be.visible')
same as similar step cthp general card has multiple links

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get(`a:contains("${option}")`).click({ force: true })
this should be clicking a link inside research card and your locator should reflect that 
div[class*='cthp-research'] a:contains("${option}")

2023-03-06 20:14 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.getIframeBody('iframe.entity-browser-modal-iframe').find('input.form-checkbox').first().eq(num - 1).check()
this is redundunt 
.first().eq(num - 1) - first() grabs the first element, and then you pass an index - I think you need to remove first here

2023-03-07 23:03 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/223574065-7f07a0c1-97d7-46d2-a8fb-1d6c34777e99.png)

2023-03-10 18:45 UTC, KateMashkinaNIH requested changes

2023-03-10 18:45 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get("div[class*='cthp-causes'] a").as('card').should('have.attr', 'href', replacedTestSiteSection)
so you used alias in the first line, then why are you repeating your code in the second? change it this
cy.get("div[class*='cthp-causes'] a").as('card').should('have.text', linkText)
    cy.get("@card").should('have.attr', 'href', replacedTestSiteSection)

2023-03-10 18:45 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get(`div[class='equalheight bgWhite cthp-survival'] a:contains("${title}")`).should('be.visible').and('have.attr', 'href', href)
change it to 
cy.get("div[class*='cthp-survival'] a").as('card').should('have.text', linkText)
cy.get("@card").should('have.attr', 'href', replacedTestSiteSection)

2023-03-10 18:45 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get("div[class*='cthp-screening'] a").as('card').should('have.attr', 'href', replacedTestSiteSection)
cy.get("div[class*='cthp-screening'] a").as('card').should('have.text', linkText)
cy.get("@card").should('have.attr', 'href', replacedTestSiteSection)

2023-03-13 16:20 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/224763045-45b191bc-7cff-49f1-940b-af9f683a0875.png)

2023-03-13 17:41 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/224783745-adda9f43-c7b3-448a-9bd8-8f45e1ecd5cb.png)

2023-03-13 17:52 UTC, KateMashkinaNIH approved these changes

2023-03-13 17:52 UTC, merged