(#385) CMS Translation of CTHP tests
NCIOCPL/cgov-digital-platform-acceptance-tests pull request #407
Opened 2023-03-16 20:35 UTC by alinai

Closes #385 

Added test scenarios to CancerTypeHomePage.feature.

2023-03-21 20:54 UTC, alinai commented
npm test run on dev-ac:
![image](https://user-images.githubusercontent.com/28455973/226738210-bfe6ec72-a86a-4583-a4b3-4326c52c54dd.png)

cypress test run on dev-ac:
![image](https://user-images.githubusercontent.com/28455973/226738332-a09ae855-a977-439f-92ad-610e7f98fd5c.png)

2023-03-24 15:24 UTC, KateMashkinaNIH requested changes

2023-03-29 16:40 UTC, alinai commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +        cy.get(`div[class*="${cardType}"]`).find('a').should('have.length.above', 1);
done

2023-03-29 16:42 UTC, alinai commented on cypress/e2e/CMS/$CancerTypeHomePage/index.js
> +    cy.get(`input[value="${removeBtn}"]`).should('be.visible');
@KateMashkinaNIH Updated this with the following but still getting error
And('the following cards fields are displayed with remove button translated as {string}', (removeBtn, dataTable) => {
    for (let { card } of dataTable.hashes()) {
        cy.get(`div[id*='top-paragraph-type-title']:contains("${card}")`).each($el => {
            cy.wrap($el).parent().find(`input:contains("${removeBtn}")`).should('be.visible');
        })
    }
});

![image](https://user-images.githubusercontent.com/28455973/228609183-2d8dd799-12bb-4117-9e43-cf5ac8aa2b57.png)

2023-03-29 18:28 UTC, alinai commented
Cypress test run on test-ac:
![image](https://user-images.githubusercontent.com/28455973/228633760-55845f85-6935-430a-86f4-aac43a586a75.png)

2023-03-29 21:37 UTC, alinai commented
Added the following step to $PressRelease -> index.js

And('user clicks on title with url spanish path {string} site section plus {string}', (spPath, purl) => {
    cy.get(`a[href='${spPath}${siteSection}/${purl}-${randomNum}']`).click();
});

cypress test run on test-ac:
![image](https://user-images.githubusercontent.com/28455973/228673513-897a2ce5-77c3-4965-b5db-9d4ae5678eee.png)

2023-03-30 14:04 UTC, KateMashkinaNIH approved these changes

2023-03-30 14:04 UTC, merged