(#386)Translation-Of-Cancer-Research-List-Page
NCIOCPL/cgov-digital-platform-acceptance-tests pull request #410
Opened 2023-03-17 22:04 UTC by ahmadakbaryNIH

closes # 386

2023-03-17 22:04 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/226061121-f7aa8612-cbdc-4ae6-8ec0-a19952823bfb.png)

2023-03-23 20:17 UTC, KateMashkinaNIH requested changes

2023-03-23 20:17 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$CancerResearchPageList.feature
> +
where is    Scenario: Verify translated content ?

2023-03-24 13:35 UTC, ahmadakbaryNIH commented
**Test is passes at both environment dev-ac and dev-ascf.**

![image](https://user-images.githubusercontent.com/114245453/227535491-48037c47-7162-4c38-858f-d65ae72b9060.png)
![image](https://user-images.githubusercontent.com/114245453/227535541-77103783-0f77-4fc7-95e4-3d0bbcd1e1ac.png)

2023-03-27 20:34 UTC, merged