(384)Translation-Of-Home-And-Landing-Page
NCIOCPL/cgov-digital-platform-acceptance-tests pull request #427
Opened 2023-03-31 05:13 UTC by ahmadakbaryNIH

closes # 384

2023-04-03 03:54 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/229407713-39a94d25-2582-4a3b-a1ea-1d093cde6c72.png)

2023-04-03 14:04 UTC, KateMashkinaNIH requested changes

2023-04-03 14:04 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$HomeAndLandingPage/index.js
> +    cy.get(`div[class*='contents-9-subform-field-'] label:contains("${spPath}")`).should('be.visible')
you should actually find a section provided from data table and search for the Titulo element within the scope of that section

2023-04-03 14:04 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$HomeAndLandingPage/index.js
> +And('every link in dynamic list starts with {string}', (spanolPath) => {
please change spelling of param -> espanolPath

2023-04-03 20:05 UTC, ahmadakbaryNIH commented
![image](https://user-images.githubusercontent.com/114245453/229615368-739e526a-ac33-4537-a463-ae33fba06503.png)

2023-04-06 19:08 UTC, KateMashkinaNIH approved these changes

2023-04-06 19:08 UTC, merged