(#429) CMS Translate Infographic tests
NCIOCPL/cgov-digital-platform-acceptance-tests pull request #451
Opened 2023-05-05 01:47 UTC by alinai

Closes #429 

Added tests for Infographic translation to $InfographicCreation.feature

2023-05-08 14:30 UTC, alinai commented
Test run on dev-ac:
![image](https://user-images.githubusercontent.com/28455973/236851186-3c209091-a96d-4725-8146-1354be7dc6d7.png)

2023-05-11 19:02 UTC, KateMashkinaNIH requested changes

2023-05-11 19:02 UTC, KateMashkinaNIH commented on cypress/e2e/CMS/$InfographicCreation/index.js
> +    cy.visit(`${frontEndBaseUrl}${spPath}${siteSection}/${purl}-${randomStr}`, { retryOnStatusCodeFailure: true });
this exists in common - can be removed

2023-05-11 19:47 UTC, alinai commented on cypress/e2e/CMS/$InfographicCreation/index.js
> +    cy.visit(`${frontEndBaseUrl}${spPath}${siteSection}/${purl}-${randomStr}`, { retryOnStatusCodeFailure: true });
done

2023-05-11 19:54 UTC, alinai commented
test run on test-ac after review:
![image](https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/assets/28455973/c08c1970-7e41-47f9-b9d8-a72cb3850ef9)

2023-05-11 19:55 UTC, alinai commented
Please review again @KateMashkinaNIH

2023-05-11 20:19 UTC, KateMashkinaNIH approved these changes

2023-05-11 20:19 UTC, merged